tasks:
  - init: >
      sudo apt-get install libgd-dev -y
      sudo cp ./compile /usr/bin
      sudo cp /usr/lib/gcc/x86_64-linux-gnu/9/include/omp.h /usr/include
      sudo apt install libopenmpi-dev
    command: >
      sudo cp ./compile /usr/bin
      sudo cp /usr/lib/gcc/x86_64-linux-gnu/9/include/omp.h /usr/include